version: "3"

services:
    static-site-framework:
        container_name: static-site-framework
        build: .
        ports:
            - 8000:80
        # volumes:
        #     - ./build:/usr/share/nginx/html
