name: Deploy to Diginext

# TRIGGERS
on:
  push:
    branches:
      - deploy

# ENVIRONMENT VARIABLES
env:
  CLUSTER: topgroup-k3s
  REGISTRY: digitopdockerhub-u

# CI/CD STEPS
jobs:
  docker-release:
    name: Deploy to Diginext
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Diginext
        uses: digitopvn/diginext-actions@v0
        with:
          dx_key: ${{ secrets.DX_KEY }}
          cluster: ${{ env.CLUSTER }}
          registry: ${{ env.REGISTRY }}
          port: "3000"

      

